### ISSUE TITLE
Opening urls from gntp doesn't work on windows

### ISSUE THREAD

**Issue by jhannes** [thecotne/subl-protocol#2]
When I use gntp to send a link the link is received by subl-protocol as e.g. subl:c:/file.txt, e.g.

```
import gntp.notifier
notifier = gntp.notifier.GrowlNotifier(applicationName = "a", notifications = ["a"], defaultNotifications = ["a"])
notifier.notify(noteType = "a", title = "Yo", description = "Yoyo", callback = "subl://C:/file.txt:132")
```
### Proposed fix

```
import re
# ...

    #url = url[len(protocol_name)+3:]
    url = re.sub(r"^" + protocol_name + ":(\/\/)?", "", url)
```

On Windows, it seems like I sometimes receive "subl://c:/file.txt" and sometimes "subl:c:/file.txt"

**Comment by thecotne** [comment]
@jhannes you could send pull request. i will add this in next few days
sorry for late response i don't get notifications if i am not mentioned in issue

**Comment by jhannes** [comment]
Done. :-)
