### ISSUE TITLE
Only a blank tab opens in ST3 on Windows

### ISSUE THREAD

**Issue by michaelsoutherton** [thecotne/subl-protocol#7]
Thanks for the plugin! Unfortunately I can't get it to work with Windows. It does open Sublime Text 3 but it always opens a blank tab and not the file I attempted to open.

Can you provide an example of a link to a file with a Windows path? I've tried the following with no luck:

`<a href="subl://open?url=file:///C:/Users/michael.myworkdomain/Desktop/test.txt">1</a>`
`<a href="subl://open?url=file%3A%2F%2F%2FC%3A%2FUsers%2Fmichael.myworkdomain%2FDesktop%2Ftest.txt">2</a>`
`<a href="subl://open?url=C:/Users/michael.myworkdomain/Desktop/test.txt">3</a>`
`<a href="subl://open?url=C%3A%2FUsers%2Fmichael.myworkdomain%2FDesktop%2Ftest.txt">4</a>`
`<a href="subl://file%3A%2F%2F%2FC%3A%2FUsers%2Fmichael.myworkdomain%2FDesktop%2Ftest.txt">5</a>`
`<a href="subl://file:///C:/Users/michael.myworkdomain/Desktop/test.txt">6</a>`

**Comment by thecotne** [comment]
all this links are not compatible with this plugin

here is example that will work

```html
<a href="subl://c:/Users/cotne/file.txt">edit file.txt</a>
```

---

i have double checked that this actually works with latest windows and sublime text fresh installed

**Comment by michaelsoutherton** [comment]
'Doh! The easiest format of the path, and I didn't try it.
I'm trying to get this to work with Laravel Ignition and I think their default subl://open?url=/some/file.txt format was throwing me off. Thank you!
