### ISSUE TITLE
Windows - Wrong path in registry for Sublime Text 4

### ISSUE THREAD

**Issue by coastwise** [thecotne/subl-protocol#9]
Not sure if this is a regression with ST4 or not, but after installing subl-protocol via Package Control, the protocol was registered (chrome asked for permission to use it) but subl:// links would not open the editor. I opened up the registry for the protocol and it was pointing to:

`C:\Program Files\Sublime Text\Lib\python33\sublime_text.exe`

However, there is no sublime_text.exe at that location. Modifying the registry to point to the following location fixed the issue and the protocol started working as expected:

`C:\Program Files\Sublime Text\sublime_text.exe`

PS: Thanks for the super useful package! I used it a lot on my previous workstation. I'm just setting up a new one and hit this minor snag. Cheers!

**Comment by thecotne** [comment]
should be fixed after this commit https://github.com/thecotne/subl-protocol/commit/8700489af2acad957c66e1afa563152053d18d91
